# Generated by Django 5.2.5 on 2025-08-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='reporet',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='statust',
            new_name='status',
        ),
    ]
