# Generated by Django 5.2.5 on 2025-09-06 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_students_file_report_students_image'),
        ('Teacher', '0002_teacher_cv_file_teacher_department_teacher_email_and_more'),
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='students',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='Teacher.teacher', verbose_name='المدرسون'),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='students',
            name='f_name',
            field=models.CharField(max_length=10, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='students',
            name='file_report',
            field=models.FileField(blank=True, null=True, upload_to='files/%y/%m/%d', verbose_name='ملف التقرير'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='المعدل'),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='students',
            name='l_name',
            field=models.CharField(max_length=10, verbose_name='الاسم الأخير'),
        ),
        migrations.AlterField(
            model_name='students',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20, verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='students',
            name='report',
            field=models.TextField(max_length=300, verbose_name='التقرير'),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.BooleanField(verbose_name='الحالة (فعال)'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة تعريفية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
