# Generated by Django 5.2.5 on 2025-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('specialization', models.CharField(max_length=100, verbose_name='التخصص')),
                ('is_head_of_department', models.BooleanField(default=False, verbose_name='هل هو رئيس قسم؟')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'المدرسين',
            },
        ),
    ]
