# Generated by Django 5.2.5 on 2025-08-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_reporet_students_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='file_report',
            field=models.FileField(null=True, upload_to='files/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
